version: "3"

services:
  mysql:
    image: mysql:5.7.25
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_PASSWORD: "password"
    ports:
      - 3306:3306

  redis:
    image: redis:5
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  # prometheus:
  #   image: prom/prometheus:v2.8.0
  #   volumes:
  #     - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./data/prometheus:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - '9090:9090'

  # grafana:
  #   image: grafana/grafana:6.0.2
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
  #     - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
  #   env_file:
  #     - ./etc/config.monitoring
  #   restart: always

  # jaeger: 
  #   image: jaegertracing/all-in-one:1.11.0
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14268:14268"
  #     - "9411:9411"

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: wurstmeister/kafka
  #   links:
  #     - zookeeper
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # Do not use localhost or 127.0.0.1 as the host ip if you want to run multiple brokers.
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "test:1:1"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./volumes/kafka:/kafka
