global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'grpc resources'
    scrape_interval: 3s
    static_configs:
    - targets: ['host.docker.internal:8080']
